"""Publishing and export pipeline.

Formats a ResearchReport into Markdown, JSON, a newsletter digest,
and short-form social posts, then writes them to the reports
directory under DATA_DIR.
"""

import json
import logging
import os
import time
from dataclasses import asdict

logger = logging.getLogger("ai_research_bot")

SOCIAL_MAX_CHARS = 280


def _today() -> str:
    return time.strftime("%Y-%m-%d")


def _clip(text: str, limit: int) -> str:
    text = (text or "").strip()
    if len(text) <= limit:
        return text
    return text[: limit - 1].rstrip() + "…"


# ============================================================
# MARKDOWN
# ============================================================

def _event_markdown(index: int, event) -> str:
    """Render one event as a full Markdown section."""
    lines = []

    lines.append(f"### {index}. {event.title}")
    lines.append("")
    lines.append(
        f"**Category:** {event.category} · "
        f"**Importance:** {event.importance}/10 · "
        f"**Relevance:** {event.relevance}/10 · "
        f"**Actionability:** {event.actionability}/10 · "
        f"**Confidence:** {event.confidence}% · "
        f"**Source quality:** {event.source_quality}/10"
    )
    lines.append("")

    if event.tldr:
        lines.append(f"**TL;DR** — {event.tldr}")
        lines.append("")

    if event.what_happened:
        lines.append(f"**What happened.** {event.what_happened}")
        lines.append("")

    if event.what_changed:
        lines.append(f"**What changed.** {event.what_changed}")
        lines.append("")

    if event.why_it_matters:
        lines.append(f"**Why it matters.** {event.why_it_matters}")
        lines.append("")

    if event.key_takeaways:
        lines.append("**Key takeaways**")
        lines.append("")
        for takeaway in event.key_takeaways:
            lines.append(f"- {takeaway}")
        lines.append("")

    if event.technical_architecture:
        lines.append("**Technical architecture**")
        lines.append("")
        for detail in event.technical_architecture:
            lines.append(f"- {detail}")
        lines.append("")

    if event.technical_details:
        lines.append("**Technical details**")
        lines.append("")
        for detail in event.technical_details:
            lines.append(f"- {detail}")
        lines.append("")

    if event.potential_impact:
        lines.append(f"**Potential impact.** {event.potential_impact}")
        lines.append("")

    if event.action:
        lines.append(f"**Action ({event.action_type}):** {event.action}")
        lines.append("")

    links = [f"[primary source]({event.primary_url})"]
    links += [f"[supporting]({url})" for url in event.supporting_urls[:4]]
    lines.append("Links: " + " · ".join(links))
    lines.append("")

    return "\n".join(lines)


def report_to_markdown(report, date: str | None = None) -> str:
    """Convert a ResearchReport into a full Markdown report."""
    date = date or _today()
    lines = []

    lines.append(f"# {report.report_title or 'AI Intelligence Report'}")
    lines.append("")
    lines.append(f"*{date}*")
    lines.append("")
    lines.append("## Executive summary")
    lines.append("")
    lines.append(report.executive_summary)
    lines.append("")

    if report.events:
        lines.append("## Events")
        lines.append("")
        for index, event in enumerate(report.events, start=1):
            lines.append(_event_markdown(index, event))
            lines.append("---")
            lines.append("")

    sections = [
        ("## Trends", report.trends),
        ("## Strategic implications", report.strategic_implications),
        ("## Build ideas", report.build_ideas),
        ("## Learn next", report.learn_next),
        ("## Opportunities", report.opportunities),
        ("## Things to ignore", report.things_to_ignore),
    ]

    for heading, items in sections:
        if items:
            lines.append(heading)
            lines.append("")
            for item in items:
                lines.append(f"- {item}")
            lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("*Generated by AI Research Bot.*")
    lines.append("")

    return "\n".join(lines)


# ============================================================
# JSON
# ============================================================

def report_to_json(report) -> str:
    """Serialize a ResearchReport as JSON (stable field order)."""
    payload = asdict(report)
    payload["generated_at"] = time.strftime("%Y-%m-%dT%H:%M:%S%z")
    return json.dumps(payload, ensure_ascii=False, indent=2)


# ============================================================
# NEWSLETTER DIGEST
# ============================================================

def build_newsletter(report, date: str | None = None) -> str:
    """Build a compact newsletter-style Markdown digest."""
    date = date or _today()
    lines = []

    lines.append(f"# AI Research Digest — {date}")
    lines.append("")
    if report.executive_summary:
        lines.append(report.executive_summary)
        lines.append("")

    if report.events:
        lines.append("## Top stories")
        lines.append("")
        for index, event in enumerate(report.events, start=1):
            tldr = event.tldr or event.why_it_matters or event.what_happened
            entry = f"{index}. **{event.title}**"
            if tldr:
                entry += f" — {_clip(tldr, 220)}"
            entry += f" ([link]({event.primary_url}))"
            lines.append(entry)
        lines.append("")

    if report.trends:
        lines.append("## Trends")
        lines.append("")
        for trend in report.trends[:5]:
            lines.append(f"- {trend}")
        lines.append("")

    if report.opportunities:
        lines.append("## Opportunities")
        lines.append("")
        for item in report.opportunities[:5]:
            lines.append(f"- {item}")
        lines.append("")

    lines.append("---")
    lines.append("*Delivered by AI Research Bot.*")

    return "\n".join(lines)


# ============================================================
# SOCIAL POSTS
# ============================================================

def build_social_posts(report, max_posts: int = 3) -> list[str]:
    """Build short-form posts (<= 280 chars) for the top events."""
    posts = []

    for event in report.events[:max_posts]:
        body = event.tldr or event.why_it_matters or event.what_happened
        if not body:
            continue

        link = event.primary_url
        budget = SOCIAL_MAX_CHARS - len(link) - 2  # newline + margins
        body = _clip(f"{event.title} — {body}", budget)

        posts.append(f"{body}\n{link}")

    return posts


# ============================================================
# EXPORT TO DISK
# ============================================================

def publish_report(report, out_dir: str | None = None) -> dict[str, str]:
    """Write the report in all supported formats.

    Returns a mapping of format -> file path.
    """
    from config import DATA_DIR

    date = _today()
    out_dir = out_dir or os.path.join(DATA_DIR, "reports", date)
    os.makedirs(out_dir, exist_ok=True)

    outputs = {
        "markdown": os.path.join(out_dir, "report.md"),
        "json": os.path.join(out_dir, "report.json"),
        "newsletter": os.path.join(out_dir, "newsletter.md"),
        "social": os.path.join(out_dir, "social_posts.txt"),
    }

    with open(outputs["markdown"], "w", encoding="utf-8") as f:
        f.write(report_to_markdown(report, date))

    with open(outputs["json"], "w", encoding="utf-8") as f:
        f.write(report_to_json(report))

    with open(outputs["newsletter"], "w", encoding="utf-8") as f:
        f.write(build_newsletter(report, date))

    posts = build_social_posts(report)
    with open(outputs["social"], "w", encoding="utf-8") as f:
        f.write("\n---\n".join(posts))

    logger.info(f"Published report to {out_dir}")
    return outputs
